packetbeat.interfaces.device: any

packetbeat.protocols.dns:
  ports: [53]
  include_authorities: true
  include_additionals: true

packetbeat.protocols.http:
  ports: [80, 5601, 9200, 8080, 8081, 5000, 8002]

output.elasticsearch:
  hosts: ['elasticsearch:9200']