version: '2'

services:

  elasticsearch:
    build: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
    networks:
      - elk

  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "127.0.0.1:5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  # packetbeat:
  #     build: packetbeat/
  #     volumes:
  #         - ./packetbeat/config/packetbeat.yml:/usr/share/packetbeat/packetbeat.yml
  #         - ./data/:/usr/share/packetbeat/data/
  #     networks:
  #         - elk
  #     depends_on:
  #         - elasticsearch

networks:

  elk:
    driver: bridge
